FROM rust:slim@sha256:81099830a1e1d244607b9a7a30f3ff6ecadc52134a933b4635faba24f52840c9

RUN apt-get update && apt-get install -y \
    protobuf-compiler \
    build-essential \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY Cargo.toml Cargo.lock* ./
COPY crates/ crates/
COPY rust/ rust/
COPY proto/ proto/

RUN cargo build --workspace --release
